image: endle/wine-fedora:v1

script:
  - dnf -y install mingw32-gettext gettext-devel.i686
  - cd xz
  - unset CC
  - ./autogen.sh --host=i686-w64-mingw32
  - ./configure --host=i686-w64-mingw32
  - make
  - make check
